name: sciviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.21.0
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - networkx>=2.6.0
  - jupyter>=1.0.0
  - ipywidgets>=7.6.0
  - py3Dmol
  - rdkit
  - cmcrameri
  - cmap